name: progressable_button
description: A progressable button using streams
version: 1.1.4
homepage: https://github.com/MigoTiti/flutter_progress_button

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  vibrate: ^0.0.4
  vector_math: ^2.0.8
  rxdart:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: